// <auto-generated />
using System;
using EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241124130311_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfCore.Entities.EfFieldPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsCanView")
                        .HasColumnType("bit");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FieldPermissions");
                });

            modelBuilder.Entity("EfCore.Entities.EfProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasicUnit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasicUnit = 5,
                            CreatedDate = new DateTime(2024, 8, 26, 13, 0, 15, 0, DateTimeKind.Unspecified),
                            Name = "Product 1",
                            Price = 29.09m,
                            Sku = "Sku_randomvalue1",
                            UpdatedDate = new DateTime(2024, 11, 4, 13, 0, 15, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BasicUnit = 9,
                            CreatedDate = new DateTime(2024, 10, 12, 13, 0, 15, 0, DateTimeKind.Unspecified),
                            Name = "Product 2",
                            Price = 83.70m,
                            Sku = "Sku_randomvalue2",
                            UpdatedDate = new DateTime(2024, 11, 16, 13, 0, 15, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BasicUnit = 1,
                            CreatedDate = new DateTime(2024, 11, 6, 13, 0, 15, 0, DateTimeKind.Unspecified),
                            Name = "Product 3",
                            Price = 53.17m,
                            Sku = "Sku_randomvalue3",
                            UpdatedDate = new DateTime(2024, 10, 20, 13, 0, 15, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BasicUnit = 3,
                            CreatedDate = new DateTime(2024, 9, 27, 13, 0, 15, 0, DateTimeKind.Unspecified),
                            Name = "Product 4",
                            Price = 19.42m,
                            Sku = "Sku_randomvalue4",
                            UpdatedDate = new DateTime(2024, 11, 4, 13, 0, 15, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BasicUnit = 3,
                            CreatedDate = new DateTime(2024, 8, 27, 13, 0, 15, 0, DateTimeKind.Unspecified),
                            Name = "Product 5",
                            Price = 44.10m,
                            Sku = "Sku_randomvalue5",
                            UpdatedDate = new DateTime(2024, 11, 4, 13, 0, 15, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
